[package]
name = "wasm-mutator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
wasm-mutate = { path = "wasm-tools/crates/wasm-mutate" }
wasmparser = "0.78"
wasm-tools-fuzz = {git = "https://github.com/bytecodealliance/wasm-tools"}
libc = "0.2.0"
